---
- name: Setup home server
  hosts: all
  become: true
  pre_tasks:
    - name: Load secrets with SOPS
      community.sops.load_vars:
        file: secrets/secrets.yaml
        name: secrets
  roles:
    - docker
    - nfs
    - tailscale
    - immich
