---
nfs_server: 192.168.0.7
nfs_shares:
  # Photos share for Immich
  - path: /mnt/tank/photos/Immich
    mount_point: /mnt/photos

  # Lightroom share for Immich
  - path: /mnt/tank/photos/Lightroom
    mount_point: /mnt/lightroom

  # Media Library share for Plex
  - path: /mnt/tank/media
    mount_point: /mnt/media