---
# shared vars
arr_stack_dir: "/opt/arr-stack"
arr_stack_download_dir: "/mnt/media/Downloads"

# rdt-client vars
rdt_client_dir: "{{ arr_stack_dir }}/rdt-client"
rdt_client_data_dir: "{{ rdt_client_dir }}/data"

# prowlarr vars
prowlarr_dir: "{{ arr_stack_dir }}/prowlarr"
prowlarr_config_dir: "{{ prowlarr_dir }}/config"

# radarr vars
radarr_dir: "{{ arr_stack_dir }}/radarr"
radarr_config_dir: "{{ radarr_dir }}/config"
radarr_data_dir: "{{ radarr_dir }}/data"
radarr_movie_dir: "/mnt/media/Movies"