---
- name: Ensure that dnsmasq is installed
  ansible.builtin.dnf:
    name: dnsmasq
    state: present

- name: Ensure dnsmasq config directory exists
  ansible.builtin.file:
    path: /etc/dnsmasq.d
    state: directory

- name: Deploy dnsmasq configuration
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: '0644'

- name: Enable and start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: yes

- name: Expose ports 53 TCP and UDP in firewalld for dnsmasq
  ansible.posix.firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: yes