---
- name: Ensure that Dnsmasq is installed
  ansible.builtin.dnf:
    name: dnsmasq
    state: present

- name: Ensure Dnsmasq config directory exists
  ansible.builtin.file:
    path: /etc/dnsmasq.d
    state: directory

- name: Deploy Dnsmasq configuration
  ansible.builtin.template:
    src: dns.conf.j2
    dest: /etc/dnsmasq.d/dns.conf

- name: Enable and start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: yes

- name: Expose ports 53 TCP and UDP in firewalld for dnsmasq
  ansible.posix.firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: yes