- name: Setup Docker and deploy applications
  hosts: docker
  become: true
  pre_tasks:
    - name: Load secrets with SOPS
      community.sops.load_vars:
        file: ../../secrets/secrets.yaml
        name: secrets

  roles:
    - caddy
    - immich
    - arr_stack
    - plex
