- name: Setup Podman and deploy applications
  hosts: podman
  become: true
  pre_tasks:
    - name: Load secrets with SOPS
      community.sops.load_vars:
        file: ../../secrets/secrets.yaml
        name: secrets

  roles:
    - podman
